/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.mycompany.interface_projeto;

import com.mycompany.interface_projeto.TelasUsuarios.AlunoForm;
import com.mycompany.interfacegrafica.model.Aluno;
import com.mycompany.interfacegrafica.model.Professor;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author castr
 */
public class TelaLogin extends javax.swing.JInternalFrame {
 public static ArrayList<Professor> Professores_semDisciplina;
    protected static ArrayList<Aluno> Alunos;
    protected static ArrayList<Professor> Professores;
   
    
    
    protected String usuario;
    protected String senha;
    
    protected String[] logins = {"Aluno"};
    protected String[] senhas = {"123456"};
    /**
     * Creates new form TelaLogin02
     */
    public TelaLogin() {        
        
        Alunos = new ArrayList<Aluno>();
        Professores_semDisciplina = new ArrayList<Professor>();
        Professores = new ArrayList<Professor>();
         initComponents();
    }
        public String getTxtUsuarioValue() {
        return txtUsuario.getValue().toString();
    }
    public String getTxtSenhaValue() {
        return new String(txtSenha.getPassword());
     }

    public String getUsuario() {
        return usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }

    public String getSenha() {
        return senha;
    }

    public void setSenha(String senha) {
        this.senha = senha;
    }
    public static void setArray_Aluno(Aluno novo){
        TelaLogin.Alunos.add(novo);
    }
    
    public static ArrayList<Aluno> getArray_Aluno() {
        return Alunos;
    }
     public static void setArray_ProfessorSemProf(Professor novo){
        TelaLogin.Professores_semDisciplina.add(novo);
    }
    
    public static ArrayList<Professor> getArray_Professores() {
        return Professores_semDisciplina;
    }
    public static void setArray_Professor(Professor novo) {
        Professores.add(novo);
    }

    public static ArrayList<Professor> getArray_Professor() {
        return Professores;
    }
   
      public boolean verificarUsuario() {
        // Verificar se o usuário e senha estão corretos
        for (int i = 0; i < logins.length; i++) {
            if (usuario.equals(logins[i]) && senha.equals(senhas[i])) {
                return true;
            }
        }
        return false;
      }
  

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Imagem = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        btnEntrar = new javax.swing.JButton();
        btnLimpar = new javax.swing.JButton();

        Imagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Imagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Icon.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("3ds", 0, 14)); // NOI18N
        lblUsuario.setText("Usuario:");

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("3ds", 0, 14)); // NOI18N
        jLabel1.setText("Senha:");

        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEntrar)
                        .addGap(6, 6, 6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(txtUsuario)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblUsuario)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Imagem, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrar)
                    .addComponent(btnLimpar))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed

    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        btnEntrarActionPerformed(evt);
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
    boolean ehAluno = false, ehProfessor = false;
        int i = 0;
        usuario = txtUsuario.getText();
        senha = txtSenha.getText();

        while (verificarUsuario() && i < Professores.size() && i < Alunos.size()) {
            if (usuario.equals(Professores.get(i).getID())
                    && senha.equals(Professores.get(i).getSenha())) {
                ehProfessor = true;
                
            } else if (usuario.equals(Alunos.get(i).getMatricula())
                        && senha.equals(Alunos.get(i).getSenha())) {
                ehAluno = true;
                
            }
        }

        if (verificarUsuario() && usuario.equals("usuario1") && senha.equals("senha1")) {
            JOptionPane.showMessageDialog(null, "Acesso autorizado. Bem vindo ADM");
            //armazenaTela.add();
            setVisible(false);
            TelaAdmin adm = new TelaAdmin();
            adm.setVisible(true);

        }else if(ehProfessor){
                JOptionPane.showMessageDialog(null,"Acesso autorizado. Bem vindo, Professor!");
//                dispose();
//                TelaProfessor prof = new TelaProfessor();
//                prof.setVisible(true);
        }else if(ehAluno){
                JOptionPane.showMessageDialog(null,"Acesso auttorizado. Bem vindo, Aluno!");
                
        }else JOptionPane.showMessageDialog(null, "Usuário ou senha incorretos.");
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        txtUsuario.setText("");
        txtSenha.setText("");
    }//GEN-LAST:event_btnLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Imagem;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JFormattedTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
