/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Classes_Form;
import com.mycompany.Tela_Cadastro.TelaCadastroAluno;
import com.mycompany.Tela_Cadastro.TelaCadastroDisciplina;
import com.mycompany.Tela_Cadastro.TelaCadastroProfessor;

//import com.mycompany.interface_projeto.TelasUsuarios.TelaAluno;


/**
 *
 * @author castr
 */
public class TelaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form TelaAdmin
     */
    public TelaAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        MenuPrincipal = new javax.swing.JMenuBar();
        menuArquivos = new javax.swing.JMenu();
        menuSair = new javax.swing.JMenuItem();
        menuTelaLogin2 = new javax.swing.JMenuItem();
        menuUsuario = new javax.swing.JMenu();
        menuCadAluno = new javax.swing.JMenuItem();
        menuCadProf = new javax.swing.JMenuItem();
        menuCadDisciplina = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        menuArquivos.setText("Arquivos");

        menuSair.setText("Sair");
        menuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSairActionPerformed(evt);
            }
        });
        menuArquivos.add(menuSair);

        menuTelaLogin2.setText("TelaLogin2");
        menuTelaLogin2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTelaLogin2ActionPerformed(evt);
            }
        });
        menuArquivos.add(menuTelaLogin2);

        MenuPrincipal.add(menuArquivos);

        menuUsuario.setText("Usuario");

        menuCadAluno.setText("CadastrarAluno");
        menuCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadAlunoActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCadAluno);

        menuCadProf.setText("CadastrarProfessor");
        menuCadProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadProfActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCadProf);

        menuCadDisciplina.setText("CadastrarDisciplina");
        menuCadDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadDisciplinaActionPerformed(evt);
            }
        });
        menuUsuario.add(menuCadDisciplina);

        MenuPrincipal.add(menuUsuario);

        setJMenuBar(MenuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSairActionPerformed
       dispose();
    
    }//GEN-LAST:event_menuSairActionPerformed

    private void menuCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadAlunoActionPerformed
       TelaCadastroAluno cadAluno = new TelaCadastroAluno();
       jDesktopPane1.add(cadAluno);
       cadAluno.setVisible(true);
    }//GEN-LAST:event_menuCadAlunoActionPerformed

    private void menuCadDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadDisciplinaActionPerformed
        TelaCadastroDisciplina cadDisciplina = new TelaCadastroDisciplina();
        jDesktopPane1.add(cadDisciplina);
        cadDisciplina.setVisible(true);
    }//GEN-LAST:event_menuCadDisciplinaActionPerformed

    private void menuCadProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadProfActionPerformed
        TelaCadastroProfessor cadProfessor = new TelaCadastroProfessor();
        jDesktopPane1.add(cadProfessor);
        cadProfessor.setVisible(true);
    }//GEN-LAST:event_menuCadProfActionPerformed

    private void menuTelaLogin2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTelaLogin2ActionPerformed
        TelaLogin login = new TelaLogin();
        jDesktopPane1.add(login);
        login.setVisible(true);
    }//GEN-LAST:event_menuTelaLogin2ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MenuPrincipal;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu menuArquivos;
    private javax.swing.JMenuItem menuCadAluno;
    private javax.swing.JMenuItem menuCadDisciplina;
    private javax.swing.JMenuItem menuCadProf;
    private javax.swing.JMenuItem menuSair;
    private javax.swing.JMenuItem menuTelaLogin2;
    private javax.swing.JMenu menuUsuario;
    // End of variables declaration//GEN-END:variables
}
