package com.mycompany.Tela_Cadastro;

import com.mycompany.ClassesArquivo.DaoAbstract;
import javax.swing.JOptionPane;
import com.mycompany.Classes_base.Aluno;
import com.mycompany.Classes_Form.TelaLogin;
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */


/**
 *
 * @author israe
 */
public class TelaCadastroAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaCadastroAluno
     */
    public TelaCadastroAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        lblNome = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblMatricula = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        lblConfirmaSenha = new javax.swing.JLabel();
        ButtonSalvar = new javax.swing.JButton();
        TextFieldNome = new javax.swing.JTextField();
        TextFieldEmail = new javax.swing.JTextField();
        TextFieldCPF = new javax.swing.JTextField();
        TextFieldMatricula = new javax.swing.JTextField();
        PasswordFieldSenha = new javax.swing.JPasswordField();
        PasswordFieldConfSenha = new javax.swing.JPasswordField();
        ButtonLimpar = new javax.swing.JButton();

        jFormattedTextField1.setText("jFormattedTextField1");

        setClosable(true);
        setIconifiable(true);
        setPreferredSize(new java.awt.Dimension(478, 310));

        lblNome.setText("Nome: ");

        lblEmail.setText("E - mail:");

        lblMatricula.setText("Matricula:");

        lblCpf.setText("CPF: ");

        lblSenha.setText("Senha:");

        lblConfirmaSenha.setText("Confirmar senha:");

        ButtonSalvar.setText("Salvar");
        ButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSalvarActionPerformed(evt);
            }
        });

        ButtonLimpar.setText("Limpar");
        ButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNome)
                    .addComponent(lblCpf)
                    .addComponent(lblSenha)
                    .addComponent(TextFieldNome)
                    .addComponent(TextFieldCPF)
                    .addComponent(PasswordFieldSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblEmail)
                    .addComponent(lblMatricula)
                    .addComponent(lblConfirmaSenha)
                    .addComponent(TextFieldMatricula)
                    .addComponent(PasswordFieldConfSenha)
                    .addComponent(TextFieldEmail)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(ButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonLimpar)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblEmail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCpf)
                    .addComponent(lblMatricula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConfirmaSenha)
                    .addComponent(lblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PasswordFieldConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonSalvar)
                    .addComponent(ButtonLimpar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSalvarActionPerformed
        
        String Nome = TextFieldNome.getText();
        String CPF = TextFieldCPF.getText();
        String Matricula = TextFieldMatricula.getText();
        String EMAIL = TextFieldEmail.getText();
        String Senha = PasswordFieldSenha.getText();
        String ConfirmaSenha = PasswordFieldConfSenha.getText();
        
        if (!Nome.isEmpty() && !EMAIL.isEmpty() && !CPF.isEmpty() && !Matricula.isEmpty()
                && !Senha.isEmpty() && !ConfirmaSenha.isEmpty()) {

            //Verificação de senha igual
            if (Senha.equals(ConfirmaSenha)) {

                Aluno ObjetoAluno = new Aluno();
                ObjetoAluno.setNomeString(Nome);
                ObjetoAluno.setMatricula(Matricula);
                ObjetoAluno.setCpfString(CPF);
                ObjetoAluno.setEmailString(EMAIL);
                
                String AlunoString = (ObjetoAluno.getMatricula() + ";" + ObjetoAluno.getNomeString() + ";" + ObjetoAluno.getCpfString() +
                        ";" + ObjetoAluno.getEmailString() + ";" + Senha);
                
                DaoAbstract  DAO= new DaoAbstract();
                DAO.WriterArchive("aluno.csv", AlunoString);
                
                JOptionPane.showMessageDialog(null, "Cadastro realizado!");
                
                dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Senhas diferentes!!!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Porfavor, preencha todos os campos!");
        }
        
    }//GEN-LAST:event_ButtonSalvarActionPerformed

    private void ButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLimparActionPerformed
        PasswordFieldConfSenha.setText("");
        PasswordFieldSenha.setText("");
        TextFieldCPF.setText("");
        TextFieldEmail.setText("");
        TextFieldMatricula.setText("");
        TextFieldNome.setText("");
    }//GEN-LAST:event_ButtonLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonLimpar;
    private javax.swing.JButton ButtonSalvar;
    private javax.swing.JPasswordField PasswordFieldConfSenha;
    private javax.swing.JPasswordField PasswordFieldSenha;
    private javax.swing.JTextField TextFieldCPF;
    private javax.swing.JTextField TextFieldEmail;
    private javax.swing.JTextField TextFieldMatricula;
    private javax.swing.JTextField TextFieldNome;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel lblConfirmaSenha;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblMatricula;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblSenha;
    // End of variables declaration//GEN-END:variables
}
